# ~/.tmux.conf

# Sets mouse copy.
set -g mouse on

# Decreases delay of input sequences which starts with esc.
set -sg escape-time 10

# Set space as leader key.
unbind C-b
set -g prefix C-Space
bind C-space send-prefix

